### ISSUE TITLE
把版本兼容做一下

### ISSUE THREAD

**Issue by xintenggiegie** [dongpeng66/DPDeviceInfo#1]
10.2以下版本会报警告

**Comment by dongpeng66** [comment]
会报错吗?  只是警告吗?

**Comment by xintenggiegie** [comment]
@dongpeng66 不报错，只是说你这个静态库是在10.2版本下创建的, 如果我的工程deployment target 版本低于这个值就会警告 （DPDeviceInfo.a(DPKeyChain.o)) was built for newer iOS version (10.2) than being linked (8.1)）

**Comment by dongpeng66** [comment]
这个.a文件你最好自己弄一下 或者不用(我记得我测试的时候真机有点问题),直接用源码就好,我再弄一下.a文件

**Comment by xintenggiegie** [comment]
ok。提个建议，在readme里声明一下支持的iOS版本
